services:
  - type: web
    name: chakkrit-ecommerce-api
    runtime: node
    plan: free
    region: singapore
    buildCommand: npm ci --include=dev && npm run db:push -w apps/api && npm run db:seed -w apps/api
    startCommand: npm run start -w apps/api
    envVars:
      - key: NODE_VERSION
        value: 22.23.2
      - key: DATABASE_URL
        value: file:./dev.db
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: JWT_SECRET
        generateValue: true
      - key: WEB_HOST
        fromService:
          type: web
          name: chakkrit-ecommerce-web
          property: host
    healthCheckPath: /api/health

  - type: web
    name: chakkrit-ecommerce-web
    runtime: node
    plan: free
    region: singapore
    buildCommand: npm ci --include=dev && npm run build -w apps/web
    startCommand: npm run start -w apps/web
    envVars:
      - key: NODE_VERSION
        value: 22.23.2
      - key: API_HOST
        fromService:
          type: web
          name: chakkrit-ecommerce-api
          property: host
